version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - back-net

  backend:
    image: hotel-image
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:postgresql://db:5433/hotel
      JDBC_USERNAME:
      JDBC_PASSWORD:
      MAILTRAP_USERNAME:
      MAILTRAP_PASSWORD:
    networks:
      - back-net

volumes:
  postgres_data:

networks:
  back-net:
    driver: bridge